ARG AIRFLOW_BASE_IMAGE="apache/airflow:2.3.2-python3.7"
FROM ${AIRFLOW_BASE_IMAGE}

RUN pip install --user --no-cache-dir \
    apache-airflow-providers-docker==2.7.0

USER root
ENV PYTHONPATH=/home/airflow/.local/lib/python3.7/site-packages
