version: 1
consol_log:
  level: INFO
formatters:
  simple:
    class: logging.Formatter
    format: "%(asctime)s %(name)s %(levelname)s %(message)s"
    datefmt: "%Y-%M-%D %H:%M:%S"
handlers:
  debug_handler:
    class: logging.FileHandler
    filename: logs.debug
    level: DEBUG
    formatter: simple
  warning_handler:
    class: logging.FileHandler
    filename: logs.warn
    level: WARNING
    formatter: simple
  stream_handler:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    level: cfg://consol_log.level
    formatter: simple
loggers:
  logs:
    level: DEBUG
    handlers: [debug_handler, warning_handler, stream_handler]
    propagate: no
root:
  level: DEBUG
  handlers: [debug_handler, warning_handler, stream_handler]
capture: |2
  ██████╗░██╗░░░██╗  ██╗░░██╗██████╗░███████╗███╗░░██╗██╗░░░██╗░█████╗░
  ██╔══██╗╚██╗░██╔╝  ╚██╗██╔╝██╔══██╗██╔════╝████╗░██║╚██╗░██╔╝██╔══██╗
  ██████╦╝░╚████╔╝░  ░╚███╔╝░██████╔╝█████╗░░██╔██╗██║░╚████╔╝░███████║
  ██╔══██╗░░╚██╔╝░░  ░██╔██╗░██╔══██╗██╔══╝░░██║╚████║░░╚██╔╝░░██╔══██║
  ██████╦╝░░░██║░░░  ██╔╝╚██╗██║░░██║███████╗██║░╚███║░░░██║░░░██║░░██║
  ╚═════╝░░░░╚═╝░░░  ╚═╝░░╚═╝╚═╝░░╚═╝╚══════╝╚═╝░░╚══╝░░░╚═╝░░░╚═╝░░╚═╝