dataframe:
  landmarks: ${original_work_dir}/data/train/landmarks.csv
  landmarks_train: landmarks_train.csv
  landmarks_val: landmarks_val.csv
  landmarks_test: ${original_work_dir}/data/sampleSubmission.csv
  train_size: 0.97
  shuffle: True
dataset:
  augmentatoins_train:
    _target_: detector.utils.utils.train_augmentation
    crop_size: 224
  augmentatoins_val:
    _target_: detector.utils.utils.test_augmentation
    crop_size: 224
  augmentatoins_test:
    _target_: detector.utils.utils.test_augmentation
    crop_size: 224

image_path: ${original_work_dir}/data/

#landmarks_train: data/train/landmarks_train.csv
#landmarks_val: data/train/landmarks_val.csv
#landmarks_test: data/sampleSubmission.csv
#transforms: null
#train_test_split: 0.5
