apiVersion: v1
kind: Pod
metadata:
  name: online-inference
  labels:
    app: online-inference
spec:
  containers:
    - name: inference
      image: xrenya/cont_app:v2
      ports:
        - name: api
          containerPort: 5000

      resources:
        requests:
          memory: "64Mi"
          cpu: "0.5"
        limits:
          memory: "256Mi"
          cpu: "1"

      livenessProbe:
        httpGet:
          path: /health
          port: api
        initialDelaySeconds: 10
        periodSeconds: 10
      readinessProbe:
        tcpSocket:
          port: api
        initialDelaySeconds: 11
        periodSeconds: 11